#!/usr/bin/env bash
# script to install the ufw firewall and setup a few rules on web-01

sudo ufw status
sudo apt install ufw
sudo ufw status
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status
